=== tanrr/Tanrr.VAPlugin.BMSRadio/Tanrr.VAPlugin.BMSRadio/Tanrr.VAPlugin.Radio.Schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "menuTarget": {
        "allOf": [
          { "type": "string" },
          { "maxLength": 30 }
        ]
      },
      "targetPhrases": {
        "allOf": [
          { "type": "string" },
          { "maxLength": 100 }
        ]
      },
      "menuName": {
        "allOf": [
          { "type": "string" },
          { "maxLength": 30 }
        ]
      },
      "menuNamePhrases": {
        "allOf": [
          { "type": "string" },
          { "maxLength": 100 }
        ]
      },
      "menuShow": {
        "allOf": [
          { "type": "string" },
          { "maxLength": 30 }
        ]
      },
      "menuItems": {
        "type": "array",
        "items": {
          "allOf": [
            { "type": "array" },
            { "minItems": 2 },
            { "maxItems": 3 },
            {
              "items": {
                "allOf": [
                  { "type": "string" },
                  { "maxLength": 150 }
                ]
              }
            }
          ]
        }
      }
    },
    "required": [
      "menuTarget",
      "targetPhrases",
      "menuName",
      "menuNamePhrases",
      "menuShow",
      "menuItems"
    ]
  }
}

=== tanrr/Tanrr.VAPlugin.BMSRadio/Tanrr.VAPlugin.BMSRadio/Resources/Tanrr.VAPlugin.Radio.Menus.json
[
		{
			"menuTarget": "Element",
			"targetPhrases": "Element;3",
			"menuName": "Combat 2",
			"menuNamePhrases": "Combat [Management;] 2",
			"menuShow": "EE",

			"menuItems": [
				[ "Weapons Free [Air;A A;]", "4" ],
				[ "Check My 6;Where Is He", "5", "EC2-HELP" ],
				[ "All together Now;Do It", "A" ],
				[ "Jettison Stores", "JJ" ]
			]
		},
		{
			"menuTarget": "Wingman",
			"targetPhrases": "Wingman;2",
			"menuName": "Combat 1",
			"menuNamePhrases": "Combat [Management;] 1",
			"menuShow": "W",

			"menuItems": [
				[ "Weapons Free [Air;A A;]", "4" ],
				[ "Check My 6;Where Is He", "5", "WC2-HELP" ],
				[ "All together Now;Do It", "A" ],
				[ "Jettison Stores", "JJ" ]
			]
		},
		{
			"menuTarget": "Wingman",
			"targetPhrases": "Wingman;2",
			"menuName": "Combat 2",
			"menuNamePhrases": "Combat [Management;] 2",
			"menuShow": "WW",

			"menuItems": [
				[ "Weapons Free [Air;A A;]", "4" ],
				[ "Check My 6;Where Is He", "5", "WC2-HELP" ],
				[ "All together Now;Do It", "A" ],
				[ "Jettison Stores", "JJ" ]
			]
		}
	]
